# Site settings
title: Knowledge Repository # site title
description: >- # site description
  Hyeonseung Kang's Knowledge Repository.
lang: ko-KR # default lang
timezone: Asia/Seoul # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/hyeonseungkang/hyeonseungkang.github.io # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Hyeonseung Kang # author name
  bio: >- # tell to the world
    강현승의 노하우 리포지토리.
  username: hyeonseungkang # general username
  github: hyeonseungkang # github username
  twitter:  # twitter username
  facebook:  # facebook username
  email: hyeonseung.kang.dev@gmail.com # email adress
  avatar: /assets/img/avatar.png # change with your own avatar

# URL settings
url: "https://hyeonseungkang.github.io" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
